# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Niladri Shekhar Dutt
name: Niladri Shekhar Dutt
position: Research Engineer
email: niladrishekhardutt@gmail.com
description: >-
  I am a Research Engineer at [Ready Player Me](https://readyplayer.me/) working on Generative AI x 3D.
  I completed my master's in Computer Vision at <span style="color: rgb(235, 40, 124);">University College London (UCL)</span> advised by [Prof. Niloy Mitra](http://www0.cs.ucl.ac.uk/staff/n.mitra/). 
  Previously, I was a Founding Engineer at  <span style="color: rgb(235, 40, 124);">NFTPort</span> leading machine learning from its inception through its Series A round of $26M. Prior to that, I was a visiting student at the <span style="color: rgb(235, 40, 124);">University of California, Berkeley</span>
  where I worked with Dr Brandie Nonnecke on ML x social network analysis. I have also spent time as a research intern at <span style="color: rgb(235, 40, 124);">Nvidia</span> and <span style="color: rgb(235, 40, 124);">IIT Kharagpur</span>.
  <br><br>
  I am interested in generating and editing 3D content (particularly meshes that are compatible with graphics engines) using text instructions, images or other simple modalities.  I believe solving this requires a fundamental understanding of shape design- *what makes a sofa well-designed and functional?* 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://niladridutt.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: niladridutt
github_username: niladridutt
linkedin_username: niladridutt
# google_scholar: rIZXMMAAAAAJ

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

markdown: kramdown
kramdown:
  typographic_symbols:
      ndash: —

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/