name: Check for broken links

on:
  workflow_dispatch:

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Link Checker 🔗
        uses: lycheeverse/lychee-action@v2.8.0
        with:
          fail: true
          args: >-
            --root-dir "$(pwd)"
            --exclude-path paper-template
            --exclude '^https://x\.com/'
            --exclude '^https://www\.ucl\.ac\.uk/'
            --exclude '^https://www\.turing\.ac\.uk/'
            --verbose
            --no-progress
            './**/*.html'
